-- Drop statements in correct order based on dependencies
DROP TABLE IF EXISTS Cobro_Gasto;
DROP TABLE IF EXISTS Gasto;
DROP TABLE IF EXISTS Pedido_Producto;
DROP TABLE IF EXISTS Pedido;
DROP TABLE IF EXISTS Producto;
DROP TABLE IF EXISTS Proveedor;
DROP TABLE IF EXISTS Reserva_Huesped;
DROP TABLE IF EXISTS Reserva;
DROP TABLE IF EXISTS Personal;
DROP TABLE IF EXISTS Cobro;
DROP TABLE IF EXISTS MetodoPago;
DROP TABLE IF EXISTS Habitacion;
DROP TABLE IF EXISTS TipoHabitacion;
DROP TABLE IF EXISTS HUESPED;
DROP TABLE IF EXISTS Categoria;
DROP TABLE IF EXISTS Rol;
DROP TABLE IF EXISTS Origen;
